[package]
name = "lyuu-commons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lyuu_commons"
path = "src/lib.rs"

[dependencies]
modular-bitfield = "0.11.2"

once_cell = "1.9.0"